Feature/hotspot edit mode
crafting-software/nuca-mobile pull request #20
Opened 2022-03-14 12:53 UTC by debreb

2022-03-14 13:08 UTC, debreb commented
https://user-images.githubusercontent.com/70328824/158178080-f1bae6c9-c529-4a5d-8291-3e03b2edf359.mp4

2022-03-14 14:29 UTC, mveres requested changes

2022-03-14 14:29 UTC, mveres commented on screens/AddHotspotScreen.tsx
> +      maxHeight: scaledHeight,
same here, are we sure it's needed?

2022-03-14 14:29 UTC, mveres commented on screens/AddHotspotScreen.tsx
> +      position: 'absolute',
can't we avoid absolute positioning here?

2022-03-15 17:38 UTC, debreb commented on screens/AddHotspotScreen.tsx
> +      height: scaledHeight + 28,
I'm okay with this solution, but in this case we need to ask our designer to resize some of the images,
for ex.: 
<img width="395" alt="Screenshot 2022-03-15 at 19 17 21" src="https://user-images.githubusercontent.com/70328824/158438225-5c3880bb-3158-4a86-8579-577c1283e782.png">

2022-03-16 10:40 UTC, mveres approved these changes

2022-03-16 10:40 UTC, merged